apiVersion: apps/v1
kind: Deployment
metadata:
  name: zxc-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zxc-deployment
  template:
    metadata:
      labels:
        app: zxc-deployment
    spec:
      containers:
        - name: frontend
          image: ifilyaninitmo/itdt-contained-frontend:master
          env:
            - name: REACT_APP_USERNAME
              value: "ltvnva25"
            - name: REACT_APP_COMPANY_NAME
              value: "ITMO"
